### ISSUE TITLE
Mobile optimisation required

### ISSUE THREAD

**Issue by SamAndPel** [SamAndPel/sudoku-solver#1]
CSS breakpoints don't trigger mobile view on most modern phones

**Comment by SamAndPel** [comment]
Resolved

**Comment by Soneji** [comment]
LOL

**Comment by Soneji** [comment]
Fixed with: d224d1e89eb3bf12239c7742bfa7158224d526b6 and 1e9e994066d57e07d91ee3b0f5c4058d6d350237
